
/**
 * This file is the entry point for your Cloud Functions.
 * It has been automatically generated by the Firebase CLI.
 */

const listUsersFunctions = require('./list-users');
const backupFunctions = require('./backup');

// Export all functions from the required modules
exports.listUsers = listUsersFunctions.listUsers;
exports.setUserStatus = listUsersFunctions.setUserStatus;
exports.backupCompanyData = backupFunctions.backupCompanyData;
